### PR TITLE
Implement downloadTransactions to fetch all transactions

### PR DESCRIPTION
**Pull request by marcpare**
Here is a more interesting pull request. Couldn't find a way to easily get all transactions with the existing API. Added a new `downloadTransactions` that simulates clicking "Export all transactions".

Not sure if you have any strong opinions on the naming or implementation. Tried to follow along with what was already there.

I'll can add a README note.

### CODE REVIEW

**Comment by dhleong** [comment]
How is this different from:

```javscript
getTransactions()
// ... 
getTransactions({offset:20})
// etc.
```

**Comment by marcpare** [comment]
that will only return 50 transactions

**Comment by dhleong** [comment]
That's what the offset parameter is for:

```javascript

require('pepper-mint')(username, password)
.then(function(mint) {
    console.log("Logged in...");

    return mint.getAccounts()
    .then(function(accounts) {
        var account = pickAccount(accounts);
        var name = account.accountName;
        var id = account.accountId;

        console.log("Fetching transactions for ", name);

        var args = {accountId: id, offset: 0};
        var iterate;
        iterate = function(txns) {
            var proceed = true;
            if (txns) {
                txns.forEach(function(txn) {
                    console.log(txn.date, txn.merchant, txn.amount);
                });

                if (txns.length) {
                    args.offset += txns.length;
                } else {
                    proceed = false;
                }
            }

            if (proceed) {
                console.log("Fetching", args);
                return mint.getTransactions(args).then(iterate);
            }
        }

        return iterate();
    })
}).fail(function(err) {
    console.error("Boo :(", err);
});
```

**Comment by marcpare** [comment]
So that all becomes a one-liner that makes just one HTTP request:

```js
require('pepper-mint')(username, password)
.then(function (mint) {
  return mint.downloadTransactions();
})
.then(function (transactions) {
  console.log(transactions.length); // 824    
})
```

One interesting difference is that you get more metadata with `getTransactions`. Haven't looked too closely into the differences – that extra stuff might not be useful.

**Comment by dhleong** [comment]
So a couple concerns here:

- The format is probably going to be inconsistent with `getTransactions()`
which is somewhat confusing
- No way to filter by account. Not a big deal, but it's another point of
inconsistency with the existing API.
- Memory usage. It looks like the csv parsing is going to read the entire
transaction history and turn it into a massive array. For ~800 transactions
that might be okay, but users with several years of active transaction
history could pos a problem. If pepper-mint is used exclusively in one-off
scripts even that's not a huge deal, but if it were used in anything more
complicated this could get unwieldy. I would much prefer an
iterating/streaming approach.

A simple `exportTransactionsCsv()` method that returns a Stream (or a
Promise that resolves to a Stream) might be best here. Explicitly
separating it from the normal Transactions API makes it clear the format
should not be expected to be similar, and the stream can be pipe()'d into
whatever a client might like: directly to a file for a simple CLI export
tool, csv-parse for more analysis, etc.

**Comment by dhleong** [comment]
Closing to inactivity

**Pull request closed without merging**
